version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running pre-build tasks"
      - pylint *.py  
  # build:
  #   commands:
  #     - echo "running pytest"
  #     - pytest
  post_build:
    commands:
      - echo "Post-build tasks"
  
artifacts:
  files:
    - '**/*'
