name : building and packaging height predictor

on:
  push:
    branches : [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on : ubuntu-latest
    steps:
      
      - name: login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghrc.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_REGISTRY }}

      - name: build flask-app container and oush to registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/evans-tats/height_predictor:latest
          
